name: Dump
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://bigota.d.miui.com/21.6.30/miui_LIME_21.6.30_ab170e377e_11.0.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              git clone https://github.com/HyperNotAryanX97/phoenix_firmware_dumper

       - name: Setup Dumpyara environment
         working-directory: phoenix_firmware_dumper
         run: |
              sudo bash setup.sh
              git config --global user.name "HyperNotAryanX97"
              git config --global user.email "ahirearyan2016@gmail.com"

       - name: Setup config envs
         working-directory: phoenix_firmware_dumper
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.GIT_ORG_NAME }}" > .git_orgname
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Running Dumpyara
         working-directory: phoenix_firmware_dumper
         run: |
              ./dumper.sh "$ROM_URL"
