name: Dumper
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://download.c.realme.com/osupdate/RMX2001_11_OTA_0610_all_3wVabGimdPKY.ozip

jobs:
  slim_build:
    runs-on: ubuntu-latest
    # You can use either of the ubuntu-18.04 or ubuntu-20.04 runner
    steps:
       # You might want to Checkout your repo first, but not mandatory
       - uses: actions/checkout@v2
       # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - uses: rokibhasansagar/slimhub_actions@main

       - name: Clone Dumpyara
         run: |
              git clone https://github.com/AndroidDumpsCI/firmware_dumper

       - name: Setup Dumpyara environment
         working-directory: firmware_dumper
         run: |
              sudo bash setup.sh
              git config --global user.name "HyperNotAryanX97"
              git config --global user.email "ahirearyan2016@gmail.com"

       - name: Setup config envs
         working-directory: firmware_dumper
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname

       - name: Running Dumpyara
         working-directory: firmware_dumper
         run: |
              ./dump.sh "$ROM_URL"
