name: Dump
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://mega-drive.rehan1rr22.workers.dev/0:findpath?id=1gxJI1kCTEAdxuBMdvZh4qREXQxWGRIVx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v3

       - name: Clone DumprX
         run: |
              git clone https://github.com/DumprX/DumprX

       - name: Setup DumprX environment
         working-directory: DumprX
         run: |
              sudo bash setup.sh
              git config --global user.name "HyperNotAryanX97"
              git config --global user.email "ahirearyan2016@gmail.com"

       - name: Setup config envs
         working-directory: DumprX
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Running DumprX
         working-directory: DumprX
         run: |
              ./dumper.sh "$ROM_URL"
