name: Dump
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://bn.d.miui.com/OS1.0.8.0.UNQINXM/gold_in_global_images_OS1.0.8.0.UNQINXM_20240603.0000.00_14.0_in_2721058204.tgz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v3

       - name: Clone Dumpyara
         run: |
              git clone https://github.com/AndroidDumpsCI/firmware_dumper

       - name: Setup Dumpyara environment
         working-directory: firmware_dumper
         run: |
              sudo bash setup.sh
              git config --global user.name "HyperNotAryanX97"
              git config --global user.email "ahirearyan2016@gmail.com"

       - name: Setup config envs
         working-directory: firmware_dumper
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Running Dumpyara
         working-directory: firmware_dumper
         run: |
              ./dump.sh "$ROM_URL"
